# Generated by Django 2.1.7 on 2019-02-26 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_ID', models.PositiveIntegerField()),
                ('Function_Area1_ID', models.PositiveIntegerField()),
                ('Function_Area2_ID', models.PositiveIntegerField()),
                ('Severity_Level_ID', models.PositiveIntegerField()),
                ('Days_To_Resolve', models.PositiveIntegerField()),
                ('Alert_Title', models.CharField(max_length=200)),
                ('Estimated_Downtime_ID', models.CharField(max_length=200)),
                ('Estimated_DowntimeCost_ID', models.CharField(max_length=200)),
                ('Imp_Ton', models.CharField(max_length=200)),
                ('Imp_Grade', models.CharField(max_length=200)),
                ('Imp_Recovery', models.CharField(max_length=200)),
                ('Imp_CashFlow', models.CharField(max_length=200)),
                ('Imp_SlowdownHrs', models.CharField(max_length=200)),
                ('Imp_Description', models.CharField(max_length=200)),
                ('AttachFile_URL', models.CharField(max_length=200)),
                ('Location_Coordinates', models.CharField(max_length=200)),
                ('Created_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Updated_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AlertsDropdown_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dropdown_Type', models.CharField(max_length=200)),
                ('Dropdown_Value', models.CharField(max_length=200)),
                ('Created_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Updated_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=200)),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_PhoneNo', models.CharField(max_length=200)),
                ('Customer_Role', models.CharField(max_length=200)),
                ('Region_ID', models.PositiveIntegerField()),
                ('Site_ID', models.PositiveIntegerField()),
                ('Function_ID', models.PositiveIntegerField()),
                ('Function_Area1_ID', models.PositiveIntegerField()),
                ('Function_Area2_ID', models.PositiveIntegerField()),
                ('Notification_ID', models.PositiveIntegerField()),
                ('Created_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Updated_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dropdown_Table_Associations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Function_Area2_ID', models.PositiveIntegerField()),
                ('Function_Area1_ID', models.PositiveIntegerField()),
                ('Function_ID', models.PositiveIntegerField()),
                ('Site_ID', models.PositiveIntegerField()),
                ('Created_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Updated_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
