# Generated by Django 2.1.7 on 2019-03-04 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0002_auto_20190226_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Severity_Type', models.CharField(max_length=200)),
                ('Created_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Updated_Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
