# Generated by Django 2.1.7 on 2019-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0003_severity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Notification_ID',
        ),
        migrations.AddField(
            model_name='customers',
            name='Critical_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='Informative_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='Minor_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='Moderate_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='Severe_ID',
            field=models.IntegerField(default=0),
        ),
    ]
