# Generated by Django 2.1.7 on 2019-03-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0004_auto_20190305_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Region_ID',
        ),
    ]
