# Generated by Django 2.1.7 on 2019-03-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0005_remove_customers_region_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='AttachFile_URL',
            new_name='status',
        ),
        migrations.AddField(
            model_name='alerts',
            name='Date_of_Occurance',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
