# Generated by Django 2.1.7 on 2019-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0007_auto_20190311_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='Days_To_Resolve',
            field=models.CharField(max_length=200),
        ),
    ]
