# Generated by Django 2.1.7 on 2019-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0008_auto_20190313_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='Function_ID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
