# Generated by Django 2.1.7 on 2019-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0010_auto_20190318_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='Function_ID',
            field=models.PositiveIntegerField(),
        ),
    ]
