# Generated by Django 2.1.7 on 2019-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0011_auto_20190318_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='Time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
