# Generated by Django 2.1.7 on 2019-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0016_auto_20190417_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='Escalation_Description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='Resolution_Description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='Time',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
