# Generated by Django 2.1.7 on 2019-04-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarrickGoldStrike_Services', '0017_auto_20190417_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='Owner_ID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
